name: forecast_weather
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  pull_to_refresh: 2.0.0
  google_fonts: 4.0.3
  icons_plus: 4.0.0
  weather_animation: 0.0.2
  flutter_weather_bg_null_safety: 1.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

